export const Colors = {
  light: {
    text: '#11181C',
    background: "#F0F1F3",
    tint: '#0a7ea4',
    icon: '#687076',
    mode: 'light',
    primary: '#e15184',
    surface: '#f5f5f5',
    card: '#f0f0f0',
    textSecondary: '#666',
    textLight: '#999',
    border: '#ddd',
    shadow: '#000',
    headerBackground: '#FA5455',
    headerText: 'black',
    buttonBackground: '#FA5455',
    buttonText: '#fff',
    inputBackground: '#fff',
    inputBorder: '#ddd',
    inputText: '#333',
    error: '#ff0000',
    success: '#34C759',
    badgeBackground: '#e15184',
    badgeText: 'white',
    headerView:"#ffffffff"
  },
  dark: {
    text: '#ECEDEE',
    background: '#151718',
    tint: '#fff',
    icon: '#9BA1A6',
    mode: 'dark',
    primary: 'white',
    surface: '#1e1e1e',
    card: '#2d2d2d',
    textSecondary: '#b0b0b0',
    textLight: '#808080',
    border: '#404040',
    shadow: '#000',
    headerBackground: '#1a1a1a',
    headerText: '#fff',
    buttonBackground: '#FA5455',
    buttonText: '#fff',
    inputBackground: '#2d2d2d',
    inputBorder: '#404040',
    inputText: '#fff',
    error: '#ff4444',
    success: '#34C759',
    badgeBackground: 'white',
    badgeText: '#e15184',
    headerView:"#404040"
  },
};

export type ThemeMode = 'light' | 'dark';
export type ThemeColors = typeof Colors.light | typeof Colors.dark;
